// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myzcmmocjlaajnovswuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15emNtbW9jamxhYWpub3Zzd3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjU1NDksImV4cCI6MjA2OTMwMTU0OX0.udA23pyXH3ZPwvH2Smc6H_UkWL_KVN9u0EyMgCtp5kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});